### ISSUE TITLE
Mongo CE Operator: cleanup

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/terraform-gitops-mongo-ce-operator#8]
Was: Mongo CE Operator: Add storage class manager dependency
Now: Mongo CE Operator: cleanup

We need to remove incorrect variable assignments.  The operator should never need info about instances.  Only the instance module needs that.

**Comment by triceam** [comment]
Repurposing this issue ... the mongoce operator should not require variable values required for mongoce instances.
